version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb+srv://huyhuynh0712:huy123@cluster0.mongodb.net/studentdb?retryWrites=true&w=majority

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend